base_url: <%= ENV["ALEPH_BASE_URL"] || "http://alephstage.library.nyu.edu" %>
rest_url: <%= ENV["ALEPH_REST_URL"] || "http://alephstage.library.nyu.edu:1891/rest-dlf" %>
adms:
  - NYU50
  - NYU51
  - NYU52
table_path: <%= ENV["ALEPH_TABLE_PATH"] || '/mnt/aleph_stage_tab' %>
