---
Bobst:
  sub_library: BOBST
  collection: MAIN
NYHistSoc:
  sub_library: NYHS
  collection: MAIN
Bobst Microform:
  sub_library: BOBST
  collection: MFORM
Bobst Tamiment:
  sub_library: BTAM
  collection: TAM
Bobst REF6:
  sub_library: BREF6
  collection: RF6
Bobst REF6 IntlDocs:
  sub_library: BREF6
  collection: RF6IN
Bobst SpecCol Downtown:
  sub_library: BFALE
  collection: FDOWN
IFA:
  sub_library: NIFA
  collection: MAIN
ISAW:
  sub_library: NISAW
  collection: MAIN
Cooper:
  sub_library: CU
  collection: MAIN
Cooper Periodicals:
  sub_library: CU
  collection: PERIO
Bobst SpecCol:
  sub_library: BFALE
  collection: FALES
Bobst Tamiment Microfilm:
  sub_library: BTAM
  collection: MAIN
Bobst REF1:
  sub_library: BOBST
  collection: REF1
Courant:
  sub_library: NCOUR
  collection: MAIN
NewSchool:
  sub_library: TNSFO
  collection: MAIN
Parsons:
  sub_library: TNSGI
  collection: MAIN
NewSchool Reference:
  sub_library: TNSFO
  collection: REF
NewSchool Periodicals:
  sub_library: TNSFO
  collection: PERIO   
New School Fogelman:
  sub_library: TNSFO
  collection: MAIN
New School Fogelman Archives:
  sub_library: TNSFO
  collection: ARCH
New School Fogelman Closed Stacks:
  sub_library: TNSFO
  collection: CLOSS
New School Fogelman Closed Stacks Periodicals:
  sub_library: TNSFO
  collection: CLOSP
New School Fogelman Micro:
  sub_library: TNSFO
  collection: MICRO
New School Fogelman Periodicals:
  sub_library: TNSFO
  collection: PERIO
New School University Center:
 sub_library: TNSGI
 collection: MAIN
New School University Center Audio Visual:
 sub_library: TNSGI
 collection: AV
New School University Center Periodicals:
 sub_library: TNSGI
 collection: PERIO
New School University Center Special Collections:
 sub_library: TNSGI
 collection: SPCL
New School University Center Special Collections Periodicals:
 sub_library: TNSGI
 collection: SPCLP
New School Kellen Archives:
 sub_library: TNSKE
 collection: ARCH
New School Scherman:
 sub_library: TNSSC
 collection: MAIN
New School Scherman Periodicals:
 sub_library: TNSSC
 collection: PERIO
New School Scherman Reference:
 sub_library: TNSSC
 collection: REF
Parsons Reference:
  sub_library: TNSGI
  collection: REF
Mannes:
  sub_library: TNSSC
  collection: MAIN
Courant Periodicals:
  sub_library: NCOUR
  collection: PERIO
RealEstate:
  sub_library: NREI
  collection: MAIN
ConservIFA:
  sub_library: NIFAC
  collection: MAIN
ConservIFA Periodicals:
  sub_library: NIFAC
  collection: PERIO
Bobst REF9:
  sub_library: BOBST
  collection: REF9
Cooper Reference:
  sub_library: CU
  collection: REF
Bobst Offsite:
  sub_library: BOBST
  collection: MAIN
Bobst REF1 Offsite:
  sub_library: BOBST
  collection: REF1
NYIntDes:
  sub_library: NYSID
  collection: MAIN
Cooper Mezzanine:
  sub_library: CU
  collection: MEZZ
NYHistSoc Bella C. Landauer Collection of Business and Advertising Ephemera.:
  sub_library: NYHS
  collection: LANDA
Bobst Tamiment Microform:
  sub_library: BTAM
  collection: MAIN
Bobst Ref6:
  sub_library: BREF6
  collection: RF6
Bobst Archives:
  sub_library: BOBST
  collection: ARCH
Bobst REF6 IntlRef:
  sub_library: BREF6
  collection: RF6IR
Brooklyn HistSoc Microform:
  sub_library: KBHS
  collection: MFORM
IFA Periodicals:
  sub_library: NIFA
  collection: PERIO
N-YHistSoc Bella C. Landauer Collection of Business and Advertising Ephemera.:
  sub_library: NYHS
  collection: LANDA
Bobst REF6 Index:
  sub_library: BREF6
  collection: RF6I
Bobst REF6 Desk:
  sub_library: BREF6
  collection: RF6DR
IFA Offsite:
  sub_library: NIFA
  collection: OFFSI
Bobst REF6 USDocs:
  sub_library: BREF6
  collection: RF6US
ConservIFA Periodicals:
  sub_library: NIFAC
  collection: PERIO
