base_url: "http://bobcatdev.library.nyu.edu"
institution: "NYU"
libraries:
  "BAFC": "NYU Bobst Avery Fisher Center"
  "BARCH": "NYU Bobst University Archives"
  "BCHIL": "NYU Bobst Children&#39;s Literature"
  "BFALE": "NYU Bobst Fales"
  "BHS": "Brooklyn Historical Society"
  "BLCC": "NYU Bobst Library"
  "BOBST": "NYU Bobst"
  "BREF": "NYU Bobst Reference"
  "BREF6": "NYU Bobst 6th Floor Reference"
  "BTAM": "NYU Bobst Tamiment/Wagner Archives"
  "BWEB": "NYU Restricted Internet"
  "CARCH": "Cooper Union Archives"
  "CCLOS": "Cooper Union Closed Stacks"
  "CGEN": "Cooper Union General"
  "CMEZZ": "Cooper Union Mezzanine"
  "CMICRO": "Cooper Union Microform"
  "COUR": "NYU Courant"
  "CPER": "Cooper Union Periodicals"
  "CREF": "Cooper Union Reference"
  "CRES": "Cooper Union Reserves"
  "CU": "Cooper Union"
  "CWEB": "Cooper Union Restricted Internet Resources"
  "IFA": "NYU Inst Fine Arts"
  "IFAC": "NYU Inst Fine Arts Conservation"
  "ISAW": "NYU Inst Study Ancient World"
  "KEV": "NYU Kevorkian"
  "LAPI": "NYU La Pietra (Italy)"
  "NABUD": "NYU Abu Dhabi Library (UAE)"
  "NOFFS": "NYU Offsite Storage"
  "NSFO": "New School Fogelman Library"
  "NSGI": "New School University Center"
  "NSKE": "New School Kellen Archives"
  "NSOS": "New School Offsite Storage"
  "NSSC": "New School Scherman Library"
  "NYHS": "New-York Historical Society"
  "NYHSBR": "NYHS Broadsides"
  "NYHSLAN": "NYHS Landauer"
  "NYHSM": "New-York Historical Society"
  "NYHSMAPS": "NYHS Maps"
  "NYHSMSS": "NYHS Mss Collection"
  "NYHSPAM": "NYHS Pamphlets"
  "NYHSPR": "NYHS Print Room"
  "NYHSREF": "NYHS Reference"
  "NYSID": "New York School of Interior Design"
  "REI": "NYU Real Estate"
  "TWEB": "New School Restricted Internet"
  "WEB": "Unrestricted Internet Access"
availability_statuses:
  "available": "Available"
  "unavailable": "Check Availability"
  "check_holdings": "Check Availability"

sources:
  nyu_aleph:
     base_url: "http://alephstage.library.nyu.edu"
     rest_url: "http://alephstage.library.nyu.edu:1891/rest-dlf"
     type: aleph
     class_name: NyuAleph
     sub_library_codes:
       "BARCH": "BOBST"
       "BCHIL": "BOBST"
       "BHS": "KBHS"
       "BREF": "BOBST"
       "CARCH": "CU"
       "CCLOS": "CU"
       "CGEN": "CU"
       "CMEZZ": "CU"
       "CMICRO": "CU"
       "COUR": "NCOUR"
       "CPER": "CU"
       "CREF": "CU"
       "CRES": "CU"
       "CWEB": "CU"
       "IFA": "NIFA"
       "IFAC": "NIFAC"
       "ISAW": "NISAW"
       "KEV": "NKEV"
       "LAPI": "NLAPI"
       "NSFO": "TNSFO"
       "NSGI": "TNSGI"
       "NSKE": "TNSKE"
       "NSOS": "TNSOS"
       "NSSC": "TNSSC"
       "NYHSBR": "NYHS"
       "NYHSLAN": "NYHS"
       "NYHSM": "NYHS"
       "NYHSMAPS": "NYHS"
       "NYHSMSS": "NYHS"
       "NYHSPAM": "NYHS"
       "NYHSPR": "NYHS"
       "NYHSREF": "NYHS"
       "REI": "NREI"
     local_base: "PRIMOCOMMON"
     institution_codes:
       BOBST: NYU
       BAFC: NYU
       BFALE: NYU
       BLCC: NYU
       BREF6: NYU
       BRES: NYU
       BTAM: NYU
       CU: CU
       KBHS: BHS
       NCOUR: NYU
       NIFA: NYU
       NIFAC: NYU
       NISAW: NYU
       NKEV: NYU
       NLAPI: NYU
       NOFFS: NYU
       NPOLY: NYU
       NREI: NYU
       NSHEQ: NYU
       NSHNG: NYU
       NYHS: NYHS
       NYSID: NYSID
       TNSFO: NS
       TNSGI: NS
       TNSKE: NS
       TNSOS: NS
       TNSSC: NS
       NABUD: NYUAD
       NADEQ: NYUAD
       NADEX: NYUAD
       NAFC: NYUAD
     requestable_statuses: ["checked_out", "offsite", available_requestable, "Depository", "Offsite Available"]
     requestable_collections: ["checked_out", "offsite", available_requestable, "Depository", "Offsite Available"]
  COURSES:
     base_url: "http://alephstage.library.nyu.edu"
     rest_url: "http://alephstage.library.nyu.edu:1891/rest-dlf"
     type: aleph
     class_name: NyuAlephReserves
     local_base: "PRIMOCOMMON"
     institution_codes:
       BOBST: NYU
       BAFC: NYU
       BFALE: NYU
       BLCC: NYU
       BREF6: NYU
       BRES: NYU
       BTAM: NYU
       CU: CU
       KBHS: BHS
       NCOUR: NYU
       NIFA: NYU
       NIFAC: NYU
       NISAW: NYU
       NKEV: NYU
       NLAPI: NYU
       NOFFS: NYU
       NPOLY: NYU
       NREI: NYU
       NSHEQ: NYU
       NSHNG: NYU
       NYHS: NYHS
       NYSID: NYSID
       TNSFO: NS
       TNSGI: NS
       TNSKE: NS
       TNSOS: NS
       TNSSC: NS
       NABUD: NYUAD
       NADEQ: NYUAD
       NADEX: NYUAD
       NAFC: NYUAD
     statuses:
       available: ["On Shelf", "Available"]
       requested: ["Requested"]
       request_ill: ["Request ILL"]
       billed_as_lost: ["Billed as Lost", "Claimed Returned"]
       offsite: ["Offsite Available"]
       checked_out: !ruby/regexp /([0-9]{2}\/[0-9]{2}\/[0-9]{2})/
       unavailable: ["Unavailable"]
       processing: ["In Processing", "In Transit"]
       ask_afc: ["Ask at Avery Fisher Center"]
       ask_archives: ["Ask at NYU Archives"]
       ask_tam: ["Ask at Tamiment"]
       ask_fales: ["Ask at Fales"]
       ask_reference: ["Ask at Reference"]
       on_exhibit: ["On Exhibit"]
       reshelving: ["Reshelving"]
  ADCOURSES:
     base_url: "http://aleph.library.nyu.edu"
     rest_url: "http://aleph.library.nyu.edu:1891/rest-dlf"
     illiad_url: "http://ill.library.nyu.edu"
     type: aleph
     class_name: NyuAlephReserves
     local_base: "PRIMOCOMMON"
     institution_codes:
       BOBST: NYU
       BAFC: NYU
       BFALE: NYU
       BLCC: NYU
       BREF6: NYU
       BRES: NYU
       BTAM: NYU
       CU: CU
       KBHS: BHS
       NCOUR: NYU
       NIFA: NYU
       NIFAC: NYU
       NISAW: NYU
       NKEV: NYU
       NLAPI: NYU
       NOFFS: NYU
       NPOLY: NYU
       NREI: NYU
       NSHEQ: NYU
       NSHNG: NYU
       NYHS: NYHS
       NYSID: NYSID
       TNSFO: NS
       TNSGI: NS
       TNSKE: NS
       TNSOS: NS
       TNSSC: NS
       NABUD: NYUAD
       NADEQ: NYUAD
       NADEX: NYUAD
       NAFC: NYUAD
     statuses:
       available: ["On Shelf", "Available"]
       requested: ["Requested"]
       request_ill: ["Request ILL"]
       billed_as_lost: ["Billed as Lost", "Claimed Returned"]
       offsite: ["Offsite Available"]
       checked_out: !ruby/regexp /([0-9]{2}\/[0-9]{2}\/[0-9]{2})/
       unavailable: ["Unavailable"]
       processing: ["In Processing", "In Transit"]
       ask_afc: ["Ask at Avery Fisher Center"]
       ask_archives: ["Ask at NYU Archives"]
       ask_tam: ["Ask at Tamiment"]
       ask_fales: ["Ask at Fales"]
       ask_reference: ["Ask at Reference"]
       on_exhibit: ["On Exhibit"]
       reshelving: ["Reshelving"]
